// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgkXzC1jAzgL1XliCTqU_hdna75wkgWcg',
    appId: '1:904526186771:web:a783b4ab18ac74f19c72e6',
    messagingSenderId: '904526186771',
    projectId: 'aquaverse-f59f4',
    authDomain: 'aquaverse-f59f4.firebaseapp.com',
    storageBucket: 'aquaverse-f59f4.firebasestorage.app',
    measurementId: 'G-JXY5ZSKKJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3oxnU8ohg98HxWHQj3tcZfcBINr8QDF0',
    appId: '1:904526186771:android:e4fc9e42595964799c72e6',
    messagingSenderId: '904526186771',
    projectId: 'aquaverse-f59f4',
    storageBucket: 'aquaverse-f59f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMsbOukXjLmwsDj2wOl4QkqHDxakbiK8',
    appId: '1:904526186771:ios:4452adfd413242509c72e6',
    messagingSenderId: '904526186771',
    projectId: 'aquaverse-f59f4',
    storageBucket: 'aquaverse-f59f4.firebasestorage.app',
    iosBundleId: 'com.palashshrote.geminiClone',
  );
}
